### ISSUE TITLE
Error running test on windows in gitBash shell.

### ISSUE THREAD

**Issue by tiagoj** [jdx/angular-boilerplate#1]
Here is the output from an attempt to run the test.  On windows 7 using the bash shell that comes with windows git.

James@JAMES-HP-12 /c/GitRepo/Web/junk/ng-tryGulp
$ npm test

> angular-boilerplate@2.0.0 test c:\GitRepo\Web\junk\ng-tryGulp
> jshint '.'  && gulp build && ./node_modules/karma/bin/karma start --single-run && protractor

ERROR: Can't open '.'
[16:44:27] Using gulpfile c:\GitRepo\Web\junk\ng-tryGulp\gulpfile.js
[16:44:27] Starting 'js'...
[16:44:27] Starting 'css'...
[16:44:28] Finished 'css' after 1.07 s
[16:44:28] Finished 'js' after 1.08 s
[16:44:28] Starting 'rev'...
4.23 ms28] Finished 'rev/' after
[16:44:28] Starting 'build'...
[16:44:28] Finished 'build' after 6.53 μs
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

**Comment by jdx** [comment]
is it the `&&`s? maybe you can't do that in Windows

**Comment by jdx** [comment]
oh wait, no it's the directory names separated by `/`

**Comment by meticoeus** [comment]
To get around this I've switched to gulp-karma and added a buiid-and-test task. I changed the package.json postinstall script to "bower install && gulp build-and-test && node server.js". Hopefully that helps anyone running into this problem.

**Comment by jdx** [comment]
I wouldn't use `gulp-karma` gulp is a build system, not a task runner. You'd be better off just having a script to exec karma correctly.
